import { useState } from "react";
import type { MouseEventHandler,} from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { LazyImage } from "@/components/RandomFox";

// random number from 1 to 122
const random = () => Math.floor(Math.random() * 122) + 1;

// Generate simple unique id
const generateId = () => Math.random().toString(36).substr(2,9)

type ImageItem = {id:string, url:string };

const Home: NextPage = () => {

  const [images, setImages] = useState<Array<ImageItem>>([ ]);

  const addNewFox: MouseEventHandler<HTMLButtonElement>= ( ) =>{
    const newImageitem : ImageItem= { 
      id:generateId(),
      url:`https://randomfox.ca/images/${random()}.jpg`
    }

    setImages([
      ...images,
      newImageitem
    ])
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center flex-col">
        <button className="bg-green-600 p-1 rounded-sm text-white " onClick={addNewFox}>add new fox</button>
        {images.map(({id,url}) => (
          <div className="p-4" key={id}>
            <LazyImage image={url} onClick={()=>{console.log("hola")}}/>
          </div>
        ))}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
